version: '3'
services:
    my-ecomm:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /usr/my-ecomm/node_modules
            - .:/usr/my-ecomm